version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: estoque.db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - estoque_pgdata:/var/lib/postgressql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U estoque -d sistema_estoque"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  estoque_pgdata: